# basic options
title: Deveb 0.1
author: deveb
email: your-email@domain.com
description: Bu proje CSS'nin tüm imkanlarını zorlayarak daha gelişmiş bir önyüz iskeleti oluşturmak için geliştirilmektedir.
twitter_username: datadeveb
github_username:  data-deveb

# Build settings
markdown: kramdown
theme: minima

# Açık bağlar
basla: /belgeler/basla
onbakis: /belgeler/basla/onbakis
belgeler: /belgeler/index
belgeler_kurulum: /belgeler/2.0/kurulum
belgeler_bakis: /belgeler/2.0/bakis
belgeler_giris: /belgeler/2.0/giris
belgeler_ogretici1: /belgeler/2.0/ogretici1
belgeler_ogretici2: /belgeler/2.0/ogretici2
belgeler_ogretici3: /belgeler/2.0/ogretici3
belgeler_ogretici4: /belgeler/2.0/ogretici4
belgeler_ogretici5: /belgeler/2.0/ogretici5
belgeler_ogretici6: /belgeler/2.0/ogretici6
belgeler_ogretici7: /belgeler/2.0/ogretici7
belgeler_paket_yapma: /belgeler/2.0/paket_yapma

basliklar_models: /belgeler/2.0/basliklar/models
basliklar_kurulum: /belgeler/2.0/basliklar/kurulum

# Ders bağları
dersler_onbakis: /diger
